# Generated by Django 2.1.5 on 2019-01-11 22:26

from django.db import migrations, models
import django.utils.timezone
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndexPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='名称')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='picture', verbose_name='图片')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=20, null=True, verbose_name='标题')),
                ('description', models.CharField(blank=True, max_length=50, null=True, verbose_name='简介')),
                ('time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='创建时间')),
                ('content', mdeditor.fields.MDTextField(verbose_name='内容')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=20, null=True, verbose_name='标题')),
                ('description', models.CharField(blank=True, max_length=50, null=True, verbose_name='简介')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='project', verbose_name='图片')),
                ('time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='创建时间')),
                ('content', mdeditor.fields.MDTextField(verbose_name='内容')),
            ],
        ),
    ]
