# Generated by Django 2.1.5 on 2019-01-21 15:46

from django.db import migrations, models
import django.utils.timezone
import imagekit.models.fields
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndexPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='名称')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='picture', verbose_name='图片')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='标题')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='简介')),
                ('time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='创建时间')),
                ('content', mdeditor.fields.MDTextField(blank=True, null=True, verbose_name='内容')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='标题')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='简介')),
                ('projectType', models.CharField(choices=[('办公楼', '办公楼'), ('教育及研究', '教育及研究 '), ('住宅', '住宅 '), ('基础设施', '基础设施 ')], default='办公楼', max_length=50, verbose_name='项目类型')),
                ('projectTime', models.DateField(blank=True, max_length=50, null=True, verbose_name='项目时间')),
                ('picture', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='project')),
                ('time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='创建时间')),
                ('content', mdeditor.fields.MDTextField(verbose_name='内容')),
            ],
        ),
    ]
