# Generated by Django 2.1.5 on 2019-01-12 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='projectTime',
            field=models.DateField(blank=True, max_length=50, null=True, verbose_name='项目时间'),
        ),
        migrations.AddField(
            model_name='project',
            name='projectType',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='项目类型'),
        ),
    ]
