# Generated by Django 2.1.5 on 2019-01-22 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20190122_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indexpicture',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='project',
            name='picture',
        ),
    ]
