# Generated by Django 2.1.5 on 2019-01-12 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20190112_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='projectType',
            field=models.CharField(choices=[('OfficeBuilding', '办公楼'), ('EducationResearch', '教育及研究 '), ('Residential', '住宅 '), ('Infrastructure', '基础设施 ')], max_length=1, verbose_name='项目类型'),
        ),
    ]
