# Generated by Django 2.1.5 on 2019-01-12 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20190112_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='projectType',
            field=models.CharField(choices=[('OfficeBuilding', '办公楼'), ('EducationResearch', '教育及研究 '), ('Residential', '住宅 '), ('Infrastructure', '基础设施 ')], default='OfficeBuilding', max_length=50, verbose_name='项目类型'),
        ),
    ]
