# Generated by Django 2.1.5 on 2019-01-13 09:23

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20190112_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='picture',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='project'),
        ),
    ]
