# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-01-13 17:23
from __future__ import unicode_literals

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20190113_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='content',
            field=mdeditor.fields.MDTextField(blank=True, null=True, verbose_name='内容'),
        ),
    ]
