# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-01-13 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_auto_20190113_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='简介'),
        ),
    ]
